"""
Every number the paper quotes, collected from the result folders into one file:
    looping_mechanism/results/paper_numbers.md   (+ .json)

    python looping_mechanism/paper_numbers.py
"""
import glob
import json
import os
import re

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MODELS = {"R1": "r1-distill-qwen-7b", "Qwen3": "qwen3-4b-thinking-2507"}


def jl(p):
    return [json.loads(l) for l in open(p)] if os.path.exists(p) else []


def rate(paths, key="truncated", keep=None):
    v = [bool(r[key]) for p in paths for r in jl(p) if keep is None or r["idx"] in keep]
    return (100 * np.mean(v), len(v)) if v else (None, 0)


def loop_rates(tag):
    N = os.path.join(ROOT, "natural_looping", "results", tag)
    C = os.path.join(ROOT, "controlled_looping", "results", tag)
    out = {}
    for temp, sub in (("t0.6", "sampled_t0.6_max12k"), ("t0", "greedy_max12k")):
        s = "seed*/" if temp == "t0.6" else ""
        nat = lambda d: glob.glob(os.path.join(N, sub, f"{s}{d}.jsonl"))  # noqa: E731
        ctl = lambda f: glob.glob(os.path.join(C, sub, f.replace("SEED", s)))  # noqa: E731
        lq = {json.loads(l)["idx"] for l in open(os.path.join(ROOT, "controlled_looping", "data", "logiqa_forms",
                                                             "minus_gold.jsonl"))}
        aq = {json.loads(l)["idx"] for l in open(os.path.join(ROOT, "controlled_looping", "data", "aqua_forms",
                                                             "minus_gold.jsonl"))}
        gq = {json.loads(l)["idx"] for l in open(os.path.join(ROOT, "controlled_looping", "data", "gsm8k_ctrl",
                                                             "catch.jsonl"))}
        rows = {
            "MATH-150 open": ctl("prompt_boxed/SEEDopen.jsonl"),
            "MATH-150 aligned": ctl("prompt_boxed/SEEDaligned.jsonl"),
            "MATH-150 catch": ctl("prompt_boxed/SEEDcatch.jsonl"),
            "GSM8K-200 aligned": ctl("gsm8k_ctrl/SEEDaligned.jsonl"),
            "GSM8K-200 catch": ctl("gsm8k_ctrl/SEEDcatch.jsonl"),
            "AQuA-227 open": ctl("aqua_forms/SEEDopen.jsonl"),
            "AQuA-227 removed": ctl("aqua_forms/SEEDminus_gold.jsonl"),
            "LogiQA-200 removed": ctl("logiqa_forms/SEEDminus_gold.jsonl"),
            "GSM8K": nat("gsm8k"), "MATH-500": nat("math500"), "AQuA": nat("aqua"), "LogiQA": nat("logiqa")}
        for k, ps in rows.items():
            out[(temp, k)] = rate(ps)
        out[(temp, "AQuA-227 original")] = rate(nat("aqua"), keep=aq)
        out[(temp, "LogiQA-200 original")] = rate(nat("logiqa"), keep=lq)
        out[(temp, "GSM8K-200 natural")] = rate(nat("gsm8k"), keep=gq)
    return out


def bench(tag):
    """per benchmark/temperature: replay correct (force/switch/switch_math) and live correct"""
    res = {}
    for d in sorted(p for p in glob.glob(os.path.join(HERE, "results", tag, "bench_switch", "*_t*")) if os.path.isdir(p)):
        b = os.path.basename(d)
        R = jl(os.path.join(d, "replay.jsonl"))
        rep = {c: (100 * np.mean([bool(r["correct"]) for r in R if r["condition"] == c]),
                   100 * np.mean([r["stop"] is not None for r in R if r["condition"] == c]),
                   sum(r["condition"] == c for r in R))
               for c in ("force", "switch", "switch_math") if any(r["condition"] == c for r in R)}
        live = {}
        s = os.path.join(d, "summary.md")
        if os.path.exists(s):
            for line in open(s):
                m = re.match(r"\| (none|force|switch|switch_math) \| (\d+) \| (\d+)% \[(\d+)-(\d+)\] \| (\d+) \| ([\d-]+) \| ([\d-]+) \|", line)
                if m:
                    live[m.group(1)] = dict(runs=int(m.group(2)), correct=int(m.group(3)), ci=(int(m.group(4)), int(m.group(5))),
                                            loops_left=int(m.group(6)), rescued=m.group(7), hurt=m.group(8))
        comp = json.load(open(os.path.join(d, "components.json"))) if os.path.exists(os.path.join(d, "components.json")) else {}
        S = jl(os.path.join(d, "signal_pairs.jsonl"))
        sig = {}
        if S:
            sig = dict(pairs=len(S), gap=float(np.mean([r["finish_logit"] - r["loop_logit"] for r in S])),
                       rec_own=100 * float(np.mean([r["recovered_own"] for r in S])),
                       rec_math=100 * float(np.mean([r["recovered_math"] for r in S])),
                       rec_ctrl=100 * float(np.mean([r["recovered_control"] for r in S])))
        res[b] = dict(replay=rep, live=live, own=comp.get("own"), signal=sig)
    return res


def main():
    L, J = ["# Numbers for the paper (generated by paper_numbers.py)", ""], {}
    for m, tag in MODELS.items():
        lr = loop_rates(tag)
        J[m] = dict(loop_rates={f"{t}|{k}": v for (t, k), v in lr.items()}, bench=bench(tag))
        L += [f"## {m}: loop rate % (runs)", "", "| condition | T=0.6 | T=0 |", "|---|---|---|"]
        for k in sorted({k for _, k in lr}):
            f = lambda t: (f"{lr[(t, k)][0]:.1f} ({lr[(t, k)][1]})" if lr.get((t, k), (None,))[0] is not None else "-")  # noqa: E731
            L.append(f"| {k} | {f('t0.6')} | {f('t0')} |")
        L += ["", f"## {m}: per-benchmark stop switch", "",
              "| bench | learn pairs | gap | patch own/math/ctrl % | own MLPs | replay correct force/switch/switch_math (n) | "
              "live correct none/force/switch/switch_math | live rescued/hurt (force) |", "|---|---|---|---|---|---|---|---|"]
        for b, v in J[m]["bench"].items():
            s, rp, lv = v["signal"], v["replay"], v["live"]
            L.append(f"| {b} | {s.get('pairs', '-')} | {s.get('gap', float('nan')):+.1f} | "
                     f"{s.get('rec_own', 0):.0f}/{s.get('rec_math', 0):.0f}/{s.get('rec_ctrl', 0):.0f} | {v['own']} | "
                     + "/".join(f"{rp[c][0]:.0f}" if c in rp else "-" for c in ("force", "switch", "switch_math"))
                     + f" ({rp.get('force', (0, 0, 0))[2]}) | "
                     + "/".join(str(lv[c]["correct"]) if c in lv else "-" for c in ("none", "force", "switch", "switch_math"))
                     + f" | {lv.get('force', {}).get('rescued', '-')}/{lv.get('force', {}).get('hurt', '-')} |")
        for f in ("why_loop", "allow_none", "switch_layers", "gate_reopen"):
            p = os.path.join(HERE, "results", tag, f, "summary.md")
            if os.path.exists(p):
                L += ["", f"## {m}: {f}", ""] + [x.rstrip() for x in open(p) if not x.startswith("# ")]
        L.append("")
    open(os.path.join(HERE, "results", "paper_numbers.md"), "w").write("\n".join(L) + "\n")
    json.dump(J, open(os.path.join(HERE, "results", "paper_numbers.json"), "w"), indent=1, default=str)
    print("\n".join(L))


if __name__ == "__main__":
    main()
